image: katalonstudio/katalon

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          # Run Test
          - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
        artifacts: # defining the artifacts .
          - report/**